# Generated by Django 6.1 on 2026-08-15 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('bonus_for', models.IntegerField(default=0, verbose_name='Bônus de Força')),
                ('bonus_dex', models.IntegerField(default=0, verbose_name='Bônus de Destreza')),
                ('bonus_con', models.IntegerField(default=0, verbose_name='Bônus de Constituição')),
                ('bonus_int', models.IntegerField(default=0, verbose_name='Bônus de Inteligência')),
                ('bonus_sab', models.IntegerField(default=0, verbose_name='Bônus de Sabedoria')),
                ('bonus_car', models.IntegerField(default=0, verbose_name='Bônus de Carisma')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassivaRacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passivas', to='core.raca')),
            ],
        ),
    ]
