# Generated by Django 6.1 on 2026-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='racas/'),
        ),
    ]
